# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e097ef8dc226c804c53b149cbba462e94352da3fa43042208e355ff8e66a4adf11462e16e2744b17aa1ac8390296c52fb124660b7e08e4977d525da258e1f29d

test:
  secret_key_base: 4db84e6414e8a5067dc71122f9c9df3bccd3976d59905b43052891a918af1ff879437449d8b6d07fbb91759762696a05e9c87b8470ff74ed9ec65105310ef944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
